### PR TITLE
Consolidate workflows

### PR DESCRIPTION
**Pull request by Tyrrrz**
This is my attempt to consolidate workflows from 2 to 1.

Highlights:
- Only one workflow, high step reuse.
- Makes use of multiple jobs. This is useful when the workflow fails, as this setup allows us to rerun only individual parts of the pipeline, instead of the whole thing.
- Makes use of artifacts to share data between jobs, without having to rebuild or even checkout.
- Runs tests on Windows and Ubuntu, just like before. The other steps only run on Ubuntu to avoid wasting resources.
- More delicate permission control (job level instead of workflow level).

Please review this with high detail because it's hard to test locally 😅

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Should've opened it as a draft first. I'll fix the issues tomorrow. But the idea is there 🙁

**Comment by Tyrrrz** [comment]
So it turns out sharing artifacts between .NET jobs isn't as simple as I'd hoped. .NET creates a lot of files outside of the build directory and even outside of the `~/.nuget` directory. Ultimately, even if we get it right, it's going to be gigabytes of data that will take a while to upload/download between jobs -- at which point we might as well repeat some steps instead.

In the current iteration I have the following setup:
- `format` job that clones the repo and runs `dotnet format` to check for formatting issues
- `test` job that clones the repo and runs `dotnet test` on several platforms
- `pack` job that clones the repo and runs `dotnet pack` to generate `nupkg` files, and upload them as artifacts
- `deploy` job that pulls the `nupkg` files from the artifacts and pushes them to the registry

All jobs, except `deploy` run in parallel. The `deploy` job doesn't, because it needs to make sure all the other jobs succeeded before proceeding. Even though this setup leads to some repeated work (checkout, building and restoring), the parallelization benefit will likely outweigh in, resulting in faster overall execution times.

**Review by justindbaur — COMMENTED** [review]
Maybe I'm wrong for liking this but I like the 3 stage restore/build/[test|pack] (`restore`, `build --no-restore`, `<action> --no-restore --no-build`) because then I can more easily blame each stage for how long they are taking and can track how long each steps take to blame them and evaluate possible improvements can be made. Because of that I know that restore on Windows generally takes much longer than it's equivalent step on Ubuntu. 

In the same vein, before I had only tested `--framework 462` on Windows because I considered the other TFM's covered by Ubuntu. With windows generally taking longer but also having slightly less to do the hope was that we can shorten the feedback loop a little bit.

Interested in your thoughts though.

**Comment by Tyrrrz** [comment]
@justindbaur thanks for the review 🙂 

> Maybe I'm wrong for liking this but I like the 3 stage restore/build/[test|pack] (`restore`, `build --no-restore`, `<action> --no-restore --no-build`) because then I can more easily blame each stage for how long they are taking and can track how long each steps take to blame them and evaluate possible improvements can be made. Because of that I know that restore on Windows generally takes much longer than it's equivalent step on Ubuntu.

Having separate stages is still possible in this setup. The main differentiating factor is that, in this setup, those stages will be repeated across some jobs. If the goal is to measure performance of individual operations, then that can certainly be achieved – there will be more steps per job, but overall the situation won't change.

Also, note that Windows runners are generally very slow. There's a recurring issue with just the `checkout` operation taking several minutes: https://github.com/actions/checkout/issues/1186

> In the same vein, before I had only tested `--framework 462` on Windows because I considered the other TFM's covered by Ubuntu. With windows generally taking longer but also having slightly less to do the hope was that we can shorten the feedback loop a little bit.

As you can see in the original workflow, the actual restore/build/test process wasn't the issue -- checkout was what took the longest amount of time:

image

I don't think the overhead of the extra target is significant, but I can update the workflow to only run tests on `FrameworkIdentifier == '.NETFramework'` when on Windows.

**Comment by justindbaur** [comment]
@Tyrrrz When I was first setting up the jobs for multi targeting I was seeing the restore step take up a lot more time on windows, [this was a particularly bad one](https://github.com/passwordless/passwordless-dotnet/actions/runs/5897417102). I would suspect that the `dotnet test` on windows in this PR is almost fully it actually doing `restore` implicitly.

I would agree that only running `FrameworkIdentifier == '.NETFramework'` tests right now will not have a negligible affect and that's why I'm okay leaving it off right now but that is mostly because we skip all the tests in CI right now. Down the road I'd love to boot up a test container running a special version of the server for tests. Then, I would expect running 3 vs 1 to have a somewhat noticeable impact. 

So I think please do separate out the stages, but you don't need to only run framework tests on windows right now. We can easily drop that in down the road but also I bet it's a little MSBuild `Condition` work on `$(ContinuousIntegrationBuild )` that you can do pretty quickly.

**Comment by Tyrrrz** [comment]
@justindbaur Thanks for the feedback. I'll adapt the PR on Monday to incorporate your suggestions and tag you again :)

**Review by abergs — APPROVED** [review]
I think this looks good!

**Comment by Tyrrrz** [comment]
@justindbaur please review again.

Highlights:
1. Restore/build/[test/pack] stages are split now
2. Windows only runs .NET Framework targets now

**Review by justindbaur — APPROVED** [review]
Looks great! Thanks for the changes.

**Pull request merged**
