### PR TITLE
Make `ApiSecret` a required property

### PR DESCRIPTION
**Pull request by Tyrrrz**
If a property is not nullable and does not have a default value, then it must be marked as `required`. That way, if the user doesn't set it, it becomes a compile-time error and not a run-time error.

### CODE REVIEW

**Comment by abergs** [comment]
@Tyrrrz I don't have any feedback of value here - I know way to little about polyfilling. I trust you that this works.

**Comment by Tyrrrz** [comment]
@justindbaur do you have any thoughts? 🙂

**Comment by justindbaur** [comment]
We are validating that ApiSecret is non-null through: https://github.com/passwordless/passwordless-dotnet/blob/3d841dbe021e2d30382b0c0253017618b623b6f0/src/Passwordless/ServiceCollectionExtensions.cs#L16 but this doesn't happen until first construction of `IOptions<PasswordlessOptions>`. 

I'm guessing `Activator.CreateInstance<PasswordlessOptions>()` doesn't respect the `required`?

**Comment by Tyrrrz** [comment]
Yeah, it's validating at run-time, this adds compile-time validation. It won't help in the builder overload but will help in those where `PasswordlessOptions` are provided directly, including in internal code.

**Review by justindbaur — APPROVED** [review]

**Pull request merged**
