### PR TITLE
Use GHATL for test reports

### PR DESCRIPTION
**Pull request by Tyrrrz**
Adds [GHATL](https://github.com/Tyrrrz/GitHubActionsTestLogger) for reporting test results.

~~I left in `dorny/test-reporter` as well, but it might be obsolete now. Let me know if you want me to keep it or remove it.~~

Removed it

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Preview: https://github.com/passwordless/passwordless-dotnet/actions/runs/6235450258 (all tests are skipped at the moment)

image

**Review by justindbaur — APPROVED** [review]
I like it a lot, not sure if we trust the author of it though 😄. I like that it is shown on the summary vs in a separate stage. It doesn't matter as much in this workflow because there aren't that many stages but it would make a world of difference in `bitwarden/server`. 

The only downside is we can't use this for `bitwarden/clients` but since these are pretty displays meant for human consumption the fact that they use different formats is fine.

**Comment by Tyrrrz** [comment]
> I like that it is shown on the summary vs in a separate stage.

It also doesn't require any extra workflow steps :)

Do you think I should remove `dorny/test-reporter` or keep both for now?

**Comment by justindbaur** [comment]
@Tyrrrz I say we remove it.

**Review by jrmccannon — APPROVED** [review]

**Pull request merged**
